# Generated by Django 5.2.5 on 2025-08-24 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, verbose_name='ID сессии')),
                ('vote_type', models.CharField(choices=[('like', 'Лайк'), ('dislike', 'Дизлайк')], max_length=10, verbose_name='Тип голоса')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата голоса')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='quotes.quote')),
            ],
            options={
                'verbose_name': 'Голос',
                'verbose_name_plural': 'Голоса',
                'ordering': ['-created_at'],
                'unique_together': {('quote', 'session_id')},
            },
        ),
    ]
